import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import Link from 'next/link'
import styles from './page.module.css'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">

      <body >
        <nav>
          <ul className={styles.center}>
            <li ><Link href="/">Home Page</Link></li>
            <li ><Link href="/agency">Agency Page</Link></li>
            <li ><Link href="/vendors">Vendors Page</Link></li>
          </ul>
        </nav>
        <br />
        {children}
      </body>
    </html>
  )
}
